config/routes.rb
Titler::Application.routes.draw do

  resources :old_monsters

  resources :adjectives

  resources :nouns

  resources :monsters do
    get 'likeMon', :on => :member
  end

  match '/dNoun' => 'nouns#destroy', :via => :delete

  root 'monsters#random'

  

  match '/random' => 'monsters#random', :via => :get

  match '/newnoun' => 'nouns#new', :via => :get
  match '/newdescriptor' => 'adjectives#new', :via => :get

  match '/testBS1' => 'monsters#test', :via => :get

  match '/stats' => 'monsters#stats', :via => :get

end

app/models/old_monster.rb
class OldMonster < ActiveRecord::Base
end

app/controllers/old_monsters_controller.rb
class OldMonstersController < ApplicationController
  before_action :set_old_monster, only: [:show, :edit, :update, :destroy]

  # GET /old_monsters
  # GET /old_monsters.json
  def index
    @old_monsters = OldMonster.all
  end

  # GET /old_monsters/1
  # GET /old_monsters/1.json
  def show
  end

  # GET /old_monsters/new
  def new
    @old_monster = OldMonster.new
  end

  # GET /old_monsters/1/edit
  def edit
  end

  # POST /old_monsters
  # POST /old_monsters.json
  def create
    @old_monster = OldMonster.new(old_monster_params)

    respond_to do |format|
      if @old_monster.save
        format.html { redirect_to @old_monster, notice: 'Old monster was successfully created.' }
        format.json { render action: 'show', status: :created, location: @old_monster }
      else
        format.html { render action: 'new' }
        format.json { render json: @old_monster.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /old_monsters/1
  # PATCH/PUT /old_monsters/1.json
  def update
    respond_to do |format|
      if @old_monster.update(old_monster_params)
        format.html { redirect_to @old_monster, notice: 'Old monster was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @old_monster.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /old_monsters/1
  # DELETE /old_monsters/1.json
  def destroy
    @old_monster.destroy
    respond_to do |format|
      format.html { redirect_to old_monsters_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_old_monster
      @old_monster = OldMonster.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def old_monster_params
      params[:old_monster]
    end
end

app/helpers/old_monsters_helper.rb
module OldMonstersHelper
end

app/views/old_monsters/_form.html.erb
<%= form_for(@old_monster) do |f| %>
  <% if @old_monster.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@old_monster.errors.count, "error") %> prohibited this old_monster from being saved:</h2>

      <ul>
      <% @old_monster.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/old_monsters/edit.html.erb
<h1>Editing old_monster</h1>

<%= render 'form' %>

<%= link_to 'Show', @old_monster %> |
<%= link_to 'Back', old_monsters_path %>

app/views/old_monsters/index.html.erb
<h1>Listing old_monsters</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @old_monsters.each do |old_monster| %>
      <tr>
        <td><%= link_to 'Show', old_monster %></td>
        <td><%= link_to 'Edit', edit_old_monster_path(old_monster) %></td>
        <td><%= link_to 'Destroy', old_monster, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Old monster', new_old_monster_path %>

app/views/old_monsters/new.html.erb
<h1>New old_monster</h1>

<%= render 'form' %>

<%= link_to 'Back', old_monsters_path %>

app/views/old_monsters/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_old_monster_path(@old_monster) %> |
<%= link_to 'Back', old_monsters_path %>