config/routes.rb
Titler::Application.routes.draw do

  resources :old_monsters

  resources :adjectives

  resources :nouns

  resources :monsters do
    get 'likeMon', :on => :member
  end

  match '/dNoun' => 'nouns#destroy', :via => :delete

  root 'monsters#random'

  

  match '/random' => 'monsters#random', :via => :get

  match '/newnoun' => 'nouns#new', :via => :get
  match '/newdescriptor' => 'adjectives#new', :via => :get

  match '/testBS1' => 'monsters#test', :via => :get

  match '/stats' => 'monsters#stats', :via => :get

end

app/models/monster.rb
class Monster < ActiveRecord::Base
	# attr_accessible :name, :noun, :adjective
	self.per_page =  25

end

app/controllers/monsters_controller.rb
class MonstersController < ApplicationController
  before_action :set_monster, only: [:show, :edit, :update, :destroy]

  # GET /monsters
  # GET /monsters.json
  def index
    # @monsters = Monster.all

    @sortOrder = params[:sort]
    # if @sortOrder == "sortDate"
    #   @monsters = Monster.all(:order => "created_at DESC")
    # elsif @sortOrder == "sortLikes"
    #   @monsters = Monster.all(:order => "likes_count DESC")
    # else
    #   @monsters = Monster.all(:order => "likes_count DESC")
    # end

    # @monsters = Monster.paginate(:page => 1, :order => 'likes_count DESC')
    if params[:page]
        @pageN = params[:page].to_i
      else
        @pageN = 1
      end

    @perPage = Monster.per_page.ceil

    @totPgs = (Monster.count.to_f / Monster.per_page.to_f)

          

    @monsters = Monster.page(params[:page]).order("likes_count DESC")

    @pageN += 1

    respond_to do |format|
      format.html
      format.js
    end

  end

  # GET /monsters/1
  # GET /monsters/1.json
  def show
    
  end

  # GET /monsters/new
  def new
    @monster = Monster.new
    @randW = rand(4)
    @randW = @randW +1

  end

  # GET /monsters/1/edit
  def edit
  end

  # POST /monsters
  # POST /monsters.json
  def create
    @monster = Monster.new(monster_params)

    respond_to do |format|
      if @monster.save
        format.html { redirect_to @monster, notice: 'Monster was successfully created.' }
        format.json { render action: 'show', status: :created, location: @monster }
      else
        format.html { render action: 'new' }
        format.json { render json: @monster.errors, status: :unprocessable_entity }
      end
    end
  end

  def random
    @randA = rand(3)
    @randA = @randA +1
    @num_adj = Adjective.find(:all).count
    @randA = rand(@num_adj)
    @randA = @randA + 1 unless @randA > 0
    @adjective = Adjective.find(@randA).word
    @num_noun = Noun.find(:all).count
    @randN = rand(@num_noun)
    @randN = @randN + 1 unless @randN > 0
    @noun = Noun.find(@randN).word

    @TotMon = TotalMonsters.find(1)
    @TotMon.monster_count += 1
    @TotMon.save



    # @mymonster = @adjective + " " + @noun

    # @monster = Monster.new(:name => @mymonster, :noun => @noun, :adjective => @adjective)
    # @monster.save
 
  end

  def stats
    @monsters = Monster.all
    @TotMon = TotalMonsters.find(1).monster_count
    @numAdj = Adjective.count
    @numNoun = Noun.count

    
    # @kit = IMGKit.new("http://www.google.com")
    # @filename = Time.now.to_s + '.jpg'


    #@display = "<h1>OMG u broke teh intertubez!!111</h1>"
   # @display = "#{render 'stats'}"


    # @display = "'" + render_to_string(
    #   :file => "monsters/stats",
    #   :locals => { @TotMon => @TotMon, @monsters => @monsters}) + "'"


    # @kit = IMGKit.new(@display)
    # @img = @kit.to_img(:jpg)
    # @file = @kit.to_file(Rails.root + "public/imgkit_images/" + @filename)


# TO JPG
    @display =  "<h1> Monster Stats IMAGE2! </h1><div class='jumbotron'><h3><b>Monsters created:</b> #{@TotMon }</h3>
  <h3><b>Monsters saved:</b> #{ @monsters.count}</h3></div>"

    
    @filename = Time.now.to_s + '.jpg'
    @kit = IMGKit.new(@display, height: 275, width: 500, quality: 100)
    # @kit.stylesheets << "#{Rails.root}/assets/application.css"
    @kit.stylesheets << "#{Rails.root}/app/assets/stylesheets/bootstrap.min.css"
    @img = @kit.to_img(:jpg)
    @file = @kit.to_file(Rails.root + "public/imgkit_images/" + @filename)
    @loc = '../imgkit_images/' + @filename


    respond_to do |format|
     
     format.html 
     format.jpg do
        @filename = Time.now.to_s + '.jpg'
        @kit = IMGkit.new(self)
        @img = @kit.to_img(:jpg)
        @file = @kit.to_file(Rails.root + "public/imgkit_images/" + @filename)
    end

      #send_data(@kit.to_jpg, :type => "image/jpeg", :disposition => 'inline')


       # format.png do
       #    send_data(@kit.to_png, :type => "image/png", :disposition => 'inline')
       #  end

       # send_data(@kit.to_img(format.jpg),
       #      :type => "image/png", :disposition => 'inline')

    
  end

     # @filename = Time.now.to_s + '.jpg'
     #  @kit = IMGKit.new("#{/stats}")
     #  @img = @kit.to_img(:jpg)
     #  @file = @kit.to_file(Rails.root + "public/imgkit_images/" + @filename)

  end

  # def save

    

  #   @monster_id = params[:id]
  #   @monster = Monster.find(@monster_id)
  #   @monster.likes_count += 1
  #   @monster.save
  #   @sortOrder = "sortLikes"
  #   @likes = Monster.find(@monster_id).likes_count

  #   respond_to do |format|
  #     format.js
  #   end
  # end


  # PATCH/PUT /monsters/1
  # PATCH/PUT /monsters/1.json
  def update
    respond_to do |format|
      if @monster.update(monster_params)
        format.html { redirect_to @monster, notice: 'Monster was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @monster.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /monsters/1
  # DELETE /monsters/1.json
  def destroy
    @monster.destroy
    respond_to do |format|
      format.html { redirect_to monsters_url }
      format.json { head :no_content }
    end
  end

  def test
    @numBooks = 15
    @i = 1
    @monStars = []
    while @i < @numBooks + 1
      @monStars << @i
      @i += 1
    end

    respond_to do |format|
      format.html {  }
      format.json {}
    end
  end

  def likeMon
    @monster_id = params[:id]
    @monster = Monster.find(@monster_id)
    @monster.likes_count += 1
    @monster.save
    @sortOrder = "sortLikes"
    @likes = Monster.find(@monster_id).likes_count

    respond_to do |format|
      format.js
    end
  end





  private
    # Use callbacks to share common setup or constraints between actions.
    def set_monster
      @monster = Monster.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def monster_params
      params.require(:monster).permit(:name)
    end
end

app/helpers/monsters_helper.rb
module MonstersHelper
end

app/views/monsters/_form.html.erb
<%= form_for(@monster) do |f| %>
  <% if @monster.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@monster.errors.count, "error") %> prohibited this monster from being saved:</h2>

      <ul>
      <% @monster.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/monsters/edit.html.erb
<h1>Editing monster</h1>

<%= render 'form' %>

<%= link_to 'Show', @monster %> |
<%= link_to 'Back', monsters_path %>

app/views/monsters/index.html.haml
-# .row 
-# 	= params.inspect
-# 	Page Number: #{@pageN}
-# 	Total Pages: #{@totPgs}

.row
	%h1.monHeader Our Creations #{@sortOrder}
	%span.monBadge.badge.badge-danger
		= @monsters.count


%div.row
	%ul.pager.pull-left.pageNums
		- if @pageN < 3
			%li.disabled
				= link_to "Previous", "#"
		- else
			%li
				= link_to "Previous", monsters_path(:page => @pageN - 2)
		%li
			= page_entries_info
		- if @pageN > @totPgs.ceil
			%li.disabled
				= link_to "Next", "#"
		- else
			%li
				= link_to "Next", monsters_path(:page => @pageN)
	%div.btn-group.btn-group-sm.sortBtns.pull-right
		%button{:type => 'button', :class => 'btn btn-default sortDate'}
			Sort by Date
		%button{:type => 'button', :class => 'btn btn-default sortLikes'}
			Sort by Popularity
		= link_to 'Create Monster', random_path, class: "btn btn-primary", type: "button"
	

%hr


= render partial: 'shared/monsterList'
			


=link_to 'Create a new freakish monster', random_path, class: "btn btn-large btn-primary"

<!-- = link_to 'Show me all the monsters',  -->

app/views/monsters/likeMon.js.erb
console.log("here at the wall");
var aID = "#monP" + <%= j @monster_id %>;
console.log(aID);
console.log("<%= j @monster.name %>");
$(aID).text("<%= j @likes.to_s %>" + " Likes").fadeIn('fast');

// $(aID).text("hello!").fadeIn('fast');

app/views/monsters/new.html.erb
<h1>New monster</h1>

<%= @randW %>

<%= render 'form' %>

<%= link_to 'Back', monsters_path %>

app/views/monsters/random.html.haml
#Monsters.jumbotron
	%h4 You have created:
	#MyMonster
		%h1#myAdj= @adjective
		%h2#myNoun= @noun

%div.row
	%div
		%button{:type => 'button', :class => 'saveMonster btn btn-large btn-default col-lg-6'} Save
	.col-offset-6
		%button{:type => 'button', :class => 'refreshMonster btn btn-large btn-default col-lg-12'} New Monster

app/views/monsters/random.js.erb
var myAdj = $('#myAdj'),
	myNoun = $('#myNoun'),
	monDiv = $('#MyMonster'),
	newNoun = "<%= j @adjective  %>",
	newAdj = "<%= j @noun  %>";

myAdj.fadeOut('fast');

	myNoun.fadeOut('fast', function() {
	myAdj.text("<%= j @adjective %>");
	myNoun.text("<%= j @noun %>");
	myAdj.fadeIn('400');
	myNoun.fadeIn('600');

});




// myAdj.fadeIn('slow');
// $("<#%= j @adjective  %>").fadeIn('slow').prependTo('#myAdj');
// $("<#%= j @noun  %>").fadeIn('slow').html('#myNoun');
console.log("<%= j @adjective %>" + " " + "<%= j @noun  %>");

// myAdj.html("<%= j @adjective  %>");
// myNoun.html("<%= j @noun  %>");
// myAdj.fadeIn('slow');
// myNoun.fadeIn('slow');
// console.log("<%= @noun %>");

app/views/monsters/show.html.erb
<p id="notice"><%= notice %></p>

<%= @randW %>
<p>
  <strong>Name:</strong>
  <%= @monster.name %>
</p>

<%= link_to 'Edit', edit_monster_path(@monster) %> |
<%= link_to 'Back', monsters_path %>

app/views/monsters/stats.html.erb
<div class="row">
	<h1> Monster Stats IMAGE2! </h1>
	</div>
<div>
	<h3><b>Monsters created:</b> <%= @TotMon %></h3>
	<h3><b>Monsters saved:</b> <%= @monsters.count %></h3>

	<%= image_tag(@loc) %>

app/views/monsters/stats2.html.haml
.row
	%h1 Monster Stats
%div
	%h3 <b>Monsters created:</b> #{@TotMon}
	%h3 <b>Monsters saved:</b> #{@monsters.count}

app/views/monsters/test.html.erb
    <div class="container">


<div class="list-group">
	<a href="#" class="list-group-item active">
    <h3 class="list-group-item-heading">List group item heading <span class="badge pull-right"><%= @monStars.count %></span></h3>
    <p class="list-group-item-text">Showing <%= @monStars.count %> items.</p>
  </a>

	<a href="#" class="list-group-item" >
		<%= image_tag "http://lorempixel.com/50/50/abstract/", :class => 'media-object pull-left' %>
	    <div class="media-body">
	    	<h4 class="list-group-item-heading">First Item</h4>
	   	 	<p class="list-group-item-text">Ahoy!</p>
	  	</div>
  	</a>

	<!-- This looks the best by far! -->
	<% @monStars.each do |m| %>
	 	<%= link_to '#', :class => 'list-group-item' do %>
	 	<%= image_tag "http://lorempixel.com/50/50/sports/", :class => 'media-object pull-left' %>
	 	<div class="media-body">
		 	<h4 class="list-group-item-heading">Number <%= m %></h4>
		 	<p class="list-group-item-text">This is item number <%= m %> in our list</p>
	 	</div>
		<% end %>
	<% end %>
</div>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="../assets/jquery.js"></script>
    <script src="../assets/bootstrap.min.js"></script>