config/routes.rb
Titler::Application.routes.draw do

  resources :old_monsters

  resources :adjectives

  resources :nouns

  resources :monsters do
    get 'likeMon', :on => :member
  end

  match '/dNoun' => 'nouns#destroy', :via => :delete

  root 'monsters#random'

  

  match '/random' => 'monsters#random', :via => :get

  match '/newnoun' => 'nouns#new', :via => :get
  match '/newdescriptor' => 'adjectives#new', :via => :get

  match '/testBS1' => 'monsters#test', :via => :get

  match '/stats' => 'monsters#stats', :via => :get

end

app/views/shared/_adjectivelist.html.haml
%ul.list-group.wordsList
	- @adjectives.each do |a|
		%li.list-group-item
			= a.word
			= link_to 'x', adjective_path(a), method: :delete, class: "pull-right nounDelete", data: { confirm: 'Are you sure?' } 

app/views/shared/_likesLink.html.haml
= link_to likeMon_monster_path(:id => m), id: "monSter#{m.id}",class: "btn btn-small pull-right likeBtn", remote: true do 
	%i.icon-thumbs-up-alt.pull-right{id: "monStarI#{m.id}"}
	- if m.likes_count == 1
		%p{id: "monP#{m.id}"} #{m.likes_count} Like
	- else
		= "#{m.likes_count} Likes"

app/views/shared/_monsterList.html.haml
%ul.list-group.monsterList
	- @monsters.each do |m|
		%li.list-group-item{id: "monLi#{m.id}"}
			= m.name
			= link_to likeMon_monster_path(:id => m), id: "monSter#{m.id}",class: "btn btn-small pull-right likeBtn", remote: true do 
				%i.icon-thumbs-up-alt.pull-right{id: "monStarI#{m.id}"}
				- if m.likes_count == 1
					%p{id: "monP#{m.id}"} #{m.likes_count} Like
				- else
					%p{id: "monP#{m.id}"} #{m.likes_count} Likes
				
				-# = link_to m.like, like_monster_path(m), class: "btn btn-small pull-right" do
			-# %span.badge
			-# 	= m.like

app/views/shared/_navbar.html.erb
<!--     <!-- Static navbar -->
    <div class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">TitlePool</a>
        <div class="nav-collapse collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="/random">Home</a></li>
            <li class="disabled"><a href="#about">About</a></li>
            <li><a href="/testBS1">Test</a></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a href="#">Action</a></li>
                <li><a href="#">Another action</a></li>
                <li><a href="#">Something else here</a></li>
                <li class="divider"></li>
                <li class="nav-header">Nav header</li>
                <li><a href="#">Separated link</a></li>
                <li><a href="#">One more separated link</a></li>
              </ul>
            </li>
          </ul>
          <ul class="nav navbar-nav pull-right">
            <li><a href="/navbar/">Default</a></li>
            <li class="active"><a href="/navbar-static-top/">Static top</a></li>
            <li><a href="/navbar-fixed-top/">Fixed top</a></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>

app/views/shared/_navbarDD.html.erb
<!--     <!-- Static navbar -->
    <div class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand pull-left" href="#">TitlePool</a>
        <div class="nav-collapse collapse">
          <ul class="nav navbar-nav">
            <li><a href="/random">Search</a></li>
			<li><a href="#about">NAME's Books</a></li>
            <li><a href="#about">Popular</a></li>
            <li><a href="/testBS1">Test</a></li>

            </ul>
            <ul class="nav navbar-nav pull-right">
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Options<b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a href="#">Log Out</a></li>
                <li><a href="#">Edit Account</a></li>
                <li><a href="#">Report Bug</a></li>
                
                <li class="divider"></li>
                <li class="nav-header">Admin Stuff</li>
                <li><a href="#">See Userbase</a></li>
                <li><a href="#">See Params</a></li>
                <li><a href="#">One more separated link</a></li>
              </ul>
            </li>
         
<!--           <ul class="dropdown-menu pull-right" role="menu" aria-labelledby="dLabel">
			<a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
              <ul class="dropdown-menu">
                <li><a href="#">Action</a></li>
                <li><a href="#">Another action</a></li>
                <li><a href="#">Something else here</a></li>
                <li class="divider"></li>
                <li class="nav-header">Nav header</li>
                <li><a href="#">Separated link</a></li>
                <li><a href="#">One more separated link</a></li> -->
          </ul>
          

<!--           <ul class="nav navbar-nav pull-right">
            <li><a href="/navbar/">Default</a></li>
            <li class="active"><a href="/navbar-static-top/">Static top</a></li>
            <li><a href="/navbar-fixed-top/">Fixed top</a></li>
          </ul> -->



        </div><!--/.nav-collapse -->
      </div>
    </div>

app/views/shared/_nounlist.html.haml
%ul.list-group.wordsList
	- @nouns.each do |n|
		%li.list-group-item
			= n.word
			-# %button{type: "button", class: "btn btn-small btn-link nounDelete pull-right", id: "noun_#{n.id}" } x
			= link_to 'x', noun_path(n), method: :delete, class: "pull-right nounDelete", data: { confirm: 'Are you sure?' } 