config/routes.rb
Titler::Application.routes.draw do

  resources :old_monsters

  resources :adjectives

  resources :nouns

  resources :monsters do
    get 'likeMon', :on => :member
  end

  match '/dNoun' => 'nouns#destroy', :via => :delete

  root 'monsters#random'

  

  match '/random' => 'monsters#random', :via => :get

  match '/newnoun' => 'nouns#new', :via => :get
  match '/newdescriptor' => 'adjectives#new', :via => :get

  match '/testBS1' => 'monsters#test', :via => :get

  match '/stats' => 'monsters#stats', :via => :get

end

app/views/layouts/application.html (Brians-MacBook-Pro's conflicted copy 2013-08-12).erb
<!DOCTYPE html>
<html>
<head>
  <title>Titler</title>
  	<!-- <meta name="viewport" content="width=320.1,minimum-scale=1.0,maximum-scale=1.0,user-scalable=no" /> -->
  	<meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap -->
    <!-- <link href="css/bootstrap.min.css" rel="stylesheet" media="screen"> -->

  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>

<header>
	<%= render :partial => 'shared/navbarDD' %>
	</header>
	<body>

<% if notice || alert %>
       <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
       <% end %>

<%= yield %>

</div>
<hr>
<!-- <#%= link_to "I want to create a new monster, damnit!", random_path %>
<hr>
<#%= link_to "Want to add more nouns?", new_noun_path, :'data-role' => 'button' %>
<br>
<#%= link_to "...or new adjectives?", new_adjective_path, :'data-role' => 'button' %>


 -->

    <!-- JavaScript plugins (requires jQuery) -->
   <!--  <script src="http://code.jquery.com/jquery.js"></script> -->
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <!-- <script src="assets/bootstrap.min.js"></script>

    <!-- Optionally enable responsive features in IE8 -->
    <!--  <script src="assets/respond.js"></script> -->

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Titler</title>
  	<!-- <meta name="viewport" content="width=320.1,minimum-scale=1.0,maximum-scale=1.0,user-scalable=no" /> -->
  	<!-- <meta name="viewport" content="width=device-width, initial-scale=1.0"> -->
    <meta name="viewport" content="width=320.1,minimum-scale=1.0,maximum-scale=1.0,user-scalable=no" />
    <!-- Bootstrap -->
   
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
   <%= analytics_init if Rails.env.production? %>
   <link rel="shortcut icon" href="favicon16.ico"/>
</head>


<body>
  <div data-role="page">
    <% if notice || alert %>
    	<% if notice %>
           <p class="notice alert alert-success"><%= notice %></p>
       <% else %>
           <p class="alert alert-danger"><%= alert %></p>
       <% end %>
    <% end %>
    <%= yield %>
  </div>
  <hr>

  <div class="row createNewBtns">
      <span>
      <%= link_to "Top Monsters", monsters_path, class: "btn btn-primary btn-large" %>
    </span>
    <span >
      <%= link_to "Add Nouns", new_noun_path, class: "btn btn-success btn-large" %>
    </span>
    <span >
      <%= link_to "Add Descriptors", new_adjective_path, class: "btn btn-success btn-large" %>
    </span>
  </div>








</body>

</html>